2024-08-04 16:05:06,323 	|	 WARNING 	|	 Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\PythonUniversity\Urban\Homework\homework42(12.4)_Logging\tests_12_4.py", line 24, in test_run
    self.second_runner = rt_with_exceptions.Runner(name=123, speed=cur_speed)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonUniversity\Urban\Homework\homework42(12.4)_Logging\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-08-04 16:05:06,325 	|	 WARNING 	|	 Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\PythonUniversity\Urban\Homework\homework42(12.4)_Logging\tests_12_4.py", line 13, in test_walk
    self.first_runner = rt_with_exceptions.Runner(name='First', speed=cur_speed)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonUniversity\Urban\Homework\homework42(12.4)_Logging\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
